logging:
    level:
        tk.mybatis: DEBUG
        com.cnpc.admin: DEBUG
spring:
    application:
        name: esp-admin
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/esp-admin?useUnicode=true&characterEncoding=UTF8
        username: root
        password: billjiang
        #url: jdbc:mysql://10.27.213.67:3306/esp-admin?useUnicode=true&characterEncoding=UTF8
        #username: root
        #password: mysql
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    basepackage: com.cnpc.admin.mapper
    xmlLocation: classpath:mapper/**/*.xml
    # id 主键生成
    mappers: tk.mybatis.mapper.common.Mapper
    identity: SELECT REPLACE(UUID(),'-','')
    order: BEFORE
    typeAliasesPackage: com.cnpc.admin.entity

server:
    port: 8085

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
        instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
#            defaultZone: http://center:8761/eureka/
swagger:
    basepackage: com.cnpc.admin
    service:
        name: user center for AdminESP
        description: AdminESP 用户中心
        developer: billjiang


---
spring:
  profiles: docker
  datasource:
    name: test
    url: jdbc:mysql://mysql-admin:3306/esp-admin?useUnicode=true&characterEncoding=UTF8
    username: root
    password: billjiang
    #url: jdbc:mysql://10.27.213.67:3306/esp-admin?useUnicode=true&characterEncoding=UTF8
    #username: root
    #password: mysql
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
server:
    port: ${{SERVER_PORT}:8085}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST}
